### ISSUE TITLE
clownface

### ISSUE THREAD

**Issue by danja** [zazukoians/rdf-ext#29]
Reto mentioned clownface in passing, without telling me what it is. I've found clownface.js, but remain pretty clueless. Could you please explain..?

**Comment by ckristo** [comment]
Maybe the Clownface examples from @bergos are helpful, see https://github.com/zazukoians/rdfjs-primer/tree/master/samples

**Comment by bergos** [comment]
@ckristo Thanks for reminding me. I added a link to the README.md.
