### ISSUE TITLE
support prefix mapping in JSON-LD

### ISSUE THREAD

**Issue by semanticfire** [zazukoians/rdf-ext#30]
Please add support to map the @context prefix mapping to the internal prefix mapping.

by using all names from values in @context which end with either '/' or '#' you'll get the full list of JSON-LD supplied prefix mappings.

**Comment by semanticfire** [comment]
This is the quick and dirty solution I use
    var data = jQuery.parseJSON(jQuery('script[type="application/ld+json"]').html())
      var context = data['@context'];
      $.each(context, function(key, value) {
        if (typeof value == "string" ) {
          if(value.slice(-1)=='#' || valueslice(-1) == '/')
            rdf.prefixes[key] = value;
        }
      });

**Comment by bergos** [comment]
There is now an option `importPrefixMap` for the JsonLdParser. The default value is `true`. All properties with a key != `@.*` will be added to the prefix map.
