### ISSUE TITLE
Decoupling Stores from the library and repo

### ISSUE THREAD

**Issue by nicola** [zazukoians/rdf-ext#35]
I find this work really clever, and I want to be using this in my future rdf projects.

However, most of the fiddling I have been doing has been in the browser, and I hate load the ENTIRE library (after browserifying it) to only get one of the stores (in-memory store).

The purpose of this library should be to provide **help** for others to write their own stores and not really ship different implementations (or at least they should be shipped in different packages).

So I did the following. I packaged every store I have seen online, in this repo and in others - so that other users can just require what they want (*the node spirit, no?*):

- [rdf-store-abstract](https://www.npmjs.com/package/rdf-store-abstract)
- [rdf-store-fs](https://www.npmjs.com/package/rdf-store-fs)
- [rdf-store-inmemory](https://www.npmjs.com/package/rdf-store-inmemory)
- [rdf-store-singlegraph](https://www.npmjs.com/package/rdf-store-singlegraph)
- [rdf-store-sparql](https://www.npmjs.com/package/rdf-store-sparql)
- [rdf-store-ldp](https://www.npmjs.com/package/rdf-store-ldp)
- [rdf-store-rdfstore-js](https://www.npmjs.com/package/rdf-store-rdfstore-js)

In this way, we don't only decouple the code of different implementation from the library and this repo, but we also foster a whole new community of developers writing their own `rdf-store` packages - maybe a MongoDB one ? (that I actually need)

I am happy to work out a PR that would remove all the code in `rdf-ext`, add you guys in the repos and npm packages and/or move these packages under `/rdf-js`

Ciao

**Comment by nicola** [comment]
Just a little example:

```javascript
var LdpStore = require('rdf-store-ldp')
var rdf = require('rdf-ext')

var store = new LdpStore(rdf, options)
```

**Comment by bergos** [comment]
Thanks! Yesterday I thought about this topic and now a big part is already done. Great!

Some details:
- The store class should be attached to the rdf object. This is required for backwards compatibility and also for the browser bundle to make it usable for none browserify code.
- Tests should also run in the browser.
- It would be nice to use the same license in all modules. I don't care if it's MIT or Apache. rdf-ext uses MIT at the moment.

**Comment by nicola** [comment]
- Is backward compatibility a good trade-off than better design? I think long -term we will benefit from not attaching it to the rdf object:
  - what if I need to use two libraries that define the same object property name? I think we just just use the standard `nodejs` way of requiring a module and use it by itself - I would like to avoid this lib magic
  - browser code should be compiled with browserify - why would that be an issues?
  - maybe we can write something like rdf.registerStore for backward compatibility
- Ops, I misread the license, will do now
- Yes, will do (only ldp has tests right now, right?)

I am open to change my mind! :)

**Comment by nicola** [comment]
[update] I have update the licenses and added bergos on npm

**Comment by bergos** [comment]
I agree about the design in the context of node.js. But it's different for the browser. The browserify bundle adds the rdf object to the global context. This allows people to use rdf-ext in the browser without browserify/additional build step. We Node-people don't see a problem here, but it raises the barrier for people without node experience. Also it's very nice for JSFiddle examples :-) But we could handle this with an alternative entry file to build the big distribution, that we have at the moment in the dist folder. Everybody else can just require() the module.

Also this [part](http://www.w3.org/TR/rdf-interfaces/#overview-2) of the RDF-Interfaces spec defines function names with this not so nice design. How do we handle this?

There are also tests for the InMemoryStore / rdf.createStore().

**Comment by nicola** [comment]
I agree on browser users, and they must be absolutely supported (we are building this for the web, right?). In my solution I guess they would just load two different script, of which one of them is `rdf-store-ldp.js` (we can make dist files for each `rdf-store` module) and then they are set.

Parsers and serializer must be the way you define I guess.

Good, I will bring the InMemoryStore tests over!

See my PR #37

**Comment by nicola** [comment]
since #37 is merged, then I am going to close this
